### ISSUE TITLE
Expanding an endpoint of the Delivery api in the Swagger UI either is way too slow or crashes

### ISSUE THREAD

**Issue by 1ngimar** [ByteCrumb/Umbraco.Community.DeliveryApiExtensions#35] opened 2024-07-15 14:56 UTC
### Which version of the package are you using?

13.0.0

### Which Umbraco version are you using? For example: 12.2.0 - don't just write v12

13.3.2

### Bug summary

When I had this package installed (v13.0.0), expanding any endpoint of the delivery api in the Swagger UI either caused the site to crash; or if I wait for a couple of minutes then the parameters might get loaded. It is however roughly a 50/50 chance of which will occur, a crash or successful load after a couple of minutes. I can't find any error logs that describe what failed. This issue was resolved immediately after uninstalling the package. I think this might be a memory issue...?

### Steps to reproduce

I used the default appsettings, but I do not know if I have to change them. For example ContentAppWeight is -50 and the description of what it does is opaque to me at least.
There is not much content in my opinion on my site. I just created a couple of new datatypes, element-types, templates, and pages in the backoffice.

**Comment by 1ngimar** [comment] 2024-07-15 15:08
RESOLVED (in a way...)
I just realized that this is the same problem as described [here in issue 30](https://github.com/ByteCrumb/Umbraco.Community.DeliveryApiExtensions/issues/30)
I tried to disable "TypedSwagger" and that resolved my issue

**Comment by lauraneto** [comment] 2024-07-15 19:26
Hi @1ngimar ,

Thank you for reporting the issue.
As mentioned in #30, this issue is caused by Swagger UI. See https://github.com/swagger-api/swagger-ui/issues/6787.

On a good note, it looks like [Swashbuckle.AspNetCore](https://github.com/domaindrivendev/Swashbuckle.AspNetCore) finally updated to a recent version of the `Swagger UI`, so if you install the latest version of the `Swashbuckle.AspNetCore` nuget package (`6.6.2` at the moment), the client performance should be a lot better. 🙌
In my case I had a small website for which the operation to get by path wouldn't load (or would take forever) but now, after updating `Swashbuckle.AspNetCore`, it loads in 5 seconds. Unfortunately, some operations still take their time, but it's still worth giving it a try.

Let us know if it helped!

(I will close this in favor of #30)

**Closed as not planned by lauraneto** 2024-07-15 19:26 UTC
Labels: bug
